@startuml
skinparam state {
	BackgroundColor #Beige
}

state Normal1: IME OFF
state "Normal" as Normal1

state Insert2: IME OFF
state "Insert" as Insert2

state Insert3: IME ON
state "Insert" as Insert3 #Lime

state Normal4: IME OFF
state "Normal" as Normal4

state Replace5: IME OFF
state "Replace" as Replace5 #text:Red

state Normal6: IME OFF
state "Normal" as Normal6

state Insert7: IME ON
state "Insert" as Insert7 #Lime;text:Red

[*] -> Normal1
Normal1 -> Insert2: i
Insert2 --> Insert3 : <C-^>
Insert3 -> Normal4 : ESC\nor\n<C-c>
Normal4 -> Replace5 : R
Replace5 -> Normal6 : Some keys & ESC
Normal6 -> Insert7 : i
@enduml
